on:
  push:
  pull_request:

jobs:
  validate_config:
    runs-on: ubuntu-latest
    env:
      PROXY_PORT: 8080
      PROXY_USERNAME: ci-user
      PROXY_PASSWORD: ci-password
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Validate Caddyfile formatting
        run: ./caddy fmt --diff ./Caddyfile
      - name: Validate Caddyfile config
        run: ./caddy validate --config ./Caddyfile

  deploy_dev:
    needs: validate_config
    if: github.ref == 'refs/heads/develop'
    uses: 18F/analytics-egress-proxy/.github/workflows/deploy.yml@develop
    with:
      APP_NAME: ${{ vars.APP_NAME_DEV }}
      CF_ORGANIZATION_NAME: ${{ vars.CF_ORGANIZATION_NAME }}
      CF_SPACE_NAME: ${{ vars.CF_SPACE_NAME }}
      ENVIRONMENT: dev
      PROXY_PORT: ${{ vars.PROXY_PORT }}
    secrets:
      CF_USERNAME: ${{ secrets.CF_USERNAME }}
      CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      PROXY_CERT: ${{ secrets.PROXY_CERT }}
      PROXY_KEY: ${{ secrets.PROXY_KEY }}
      PROXY_USERNAME: ${{ secrets.PROXY_USERNAME_DEV }}
      PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD_DEV }}
  deploy_stg:
    needs: validate_config
    if: github.ref == 'refs/heads/staging'
    uses: 18F/analytics-egress-proxy/.github/workflows/deploy.yml@develop
    with:
      APP_NAME: ${{ vars.APP_NAME_STG }}
      CF_ORGANIZATION_NAME: ${{ vars.CF_ORGANIZATION_NAME }}
      CF_SPACE_NAME: ${{ vars.CF_SPACE_NAME }}
      ENVIRONMENT: stg
      PROXY_PORT: ${{ vars.PROXY_PORT }}
    secrets:
      CF_USERNAME: ${{ secrets.CF_USERNAME }}
      CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      PROXY_CERT: ${{ secrets.PROXY_CERT }}
      PROXY_KEY: ${{ secrets.PROXY_KEY }}
      PROXY_USERNAME: ${{ secrets.PROXY_USERNAME_STG }}
      PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD_STG }}
  deploy_prd:
    needs: validate_config
    if: github.ref == 'refs/heads/master'
    uses: 18F/analytics-egress-proxy/.github/workflows/deploy.yml@develop
    with:
      APP_NAME: ${{ vars.APP_NAME_PRD }}
      CF_ORGANIZATION_NAME: ${{ vars.CF_ORGANIZATION_NAME }}
      CF_SPACE_NAME: ${{ vars.CF_SPACE_NAME }}
      ENVIRONMENT: prd
      PROXY_PORT: ${{ vars.PROXY_PORT }}
    secrets:
      CF_USERNAME: ${{ secrets.CF_USERNAME }}
      CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      PROXY_CERT: ${{ secrets.PROXY_CERT }}
      PROXY_KEY: ${{ secrets.PROXY_KEY }}
      PROXY_USERNAME: ${{ secrets.PROXY_USERNAME_PRD }}
      PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD_PRD }}
