on:
  workflow_call:
    inputs:
      APP_NAME:
        required: true
        type: string
      CF_ORGANIZATION_NAME:
        required: true
        type: string
      CF_SPACE_NAME:
        required: true
        type: string
      PROXY_PORT:
        required: true
        type: string
    secrets:
      CF_USERNAME:
        required: true
      CF_PASSWORD:
        required: true
      PROXY_USERNAME:
        required: true
      PROXY_PASSWORD:
        required: true

env:
  APP_NAME: ${{ inputs.APP_NAME }}
  CF_USERNAME: ${{ secrets.CF_USERNAME }}
  CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
  CF_ORGANIZATION_NAME: ${{ inputs.CF_ORGANIZATION_NAME }}
  CF_SPACE_NAME: ${{ inputs.CF_SPACE_NAME }}
  PROXY_PORT: ${{ inputs.PROXY_PORT }}
  PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
  PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}

jobs:
  deploy_reporter:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Install cloud foundry CLI for interacting with cloud.gov
        run: |
          sudo curl -v -L -o cf8-cli-installer_8.7.4_x86-64.deb 'https://packages.cloudfoundry.org/stable?release=debian64&version=8.7.4'
          sudo dpkg -i cf8-cli-installer_8.7.4_x86-64.deb
      - name: Run envsubst on manifest.yml to set environment specific values
        run: |
          mv manifest.yml manifest.yml.src
          envsubst < manifest.yml.src > manifest.yml
          cat manifest.yml
      - name: Login to cloud.gov and deploy
        run: |
          set -e
          # Log into cloud.gov
          cf api api.fr.cloud.gov
          cf login -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORGANIZATION_NAME -s $CF_SPACE_NAME
          cf push -f "./manifest.yml"
          cf logout
